# Generated by Django 2.0.5 on 2018-05-18 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(default='', max_length=100)),
                ('character_info', models.CharField(blank=True, max_length=9999, null=True)),
                ('article_creation_date', models.DateTimeField(null=True, verbose_name='creation_date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllianceRaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alliance_race', models.CharField(default='', max_length=10)),
                ('alliance_text', models.CharField(default='', max_length=9999)),
            ],
            options={
                'verbose_name_plural': 'Alliance races',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='', max_length=20)),
                ('class_text', models.CharField(default='', max_length=9999)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_name', models.CharField(default='', max_length=8)),
                ('faction_text', models.CharField(default='', max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='HordeCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(default='', max_length=100)),
                ('character_info', models.CharField(blank=True, max_length=9999, null=True)),
                ('article_creation_date', models.DateTimeField(null=True, verbose_name='creation_date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('character_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.Class')),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.Faction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HordeRaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horde_race', models.CharField(default='', max_length=10)),
                ('horde_text', models.CharField(default='', max_length=9999)),
            ],
            options={
                'verbose_name_plural': 'Horde races',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.AddField(
            model_name='hordecharacter',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.HordeRaces'),
        ),
        migrations.AddField(
            model_name='hordecharacter',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.Status'),
        ),
        migrations.AddField(
            model_name='alliancecharacter',
            name='character_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.Class'),
        ),
        migrations.AddField(
            model_name='alliancecharacter',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.Faction'),
        ),
        migrations.AddField(
            model_name='alliancecharacter',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.AllianceRaces'),
        ),
        migrations.AddField(
            model_name='alliancecharacter',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.Status'),
        ),
    ]
