# Generated by Django 2.0.5 on 2018-05-14 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(default='', max_length=100)),
                ('character_info', models.CharField(default='', max_length=9999)),
                ('faction', models.CharField(choices=[('Choose', 'Choose...'), ('Alliance', 'Alliance'), ('Horde', 'Horde')], default='', max_length=8)),
                ('status', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead'), ('Incapacitated', 'Incapacitated'), ('Unknown', 'Unknown')], default='', max_length=8)),
                ('character_class', models.CharField(choices=[('Mage', 'Mage'), ('Priest', 'Priest'), ('Lock', 'Warlock'), ('DH', 'Demon Hunter'), ('Druid', 'Druid'), ('Monk', 'Monk'), ('Rogue', 'Rogue'), ('Hunter', 'Hunter'), ('Shaman', 'Shaman'), ('DK', 'Death Knight'), ('Paladin', 'Paladin'), ('Warrior', 'Warrior')], default='', max_length=20)),
                ('article_creation_date', models.DateTimeField(null=True, verbose_name='creation_date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('race', models.CharField(choices=[('Human', 'Human'), ('Dwarf', 'Dwarf'), ('Night Elf', 'Night Elf'), ('Gnome', 'Gnome'), ('Draenei', 'Draenei'), ('Worgen', 'Worgen'), ('Pandaren', 'Pandaren')], max_length=8)),
                ('article_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HordeCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(default='', max_length=100)),
                ('character_info', models.CharField(default='', max_length=9999)),
                ('faction', models.CharField(choices=[('Choose', 'Choose...'), ('Alliance', 'Alliance'), ('Horde', 'Horde')], default='', max_length=8)),
                ('status', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead'), ('Incapacitated', 'Incapacitated'), ('Unknown', 'Unknown')], default='', max_length=8)),
                ('character_class', models.CharField(choices=[('Mage', 'Mage'), ('Priest', 'Priest'), ('Lock', 'Warlock'), ('DH', 'Demon Hunter'), ('Druid', 'Druid'), ('Monk', 'Monk'), ('Rogue', 'Rogue'), ('Hunter', 'Hunter'), ('Shaman', 'Shaman'), ('DK', 'Death Knight'), ('Paladin', 'Paladin'), ('Warrior', 'Warrior')], default='', max_length=20)),
                ('article_creation_date', models.DateTimeField(null=True, verbose_name='creation_date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('race', models.CharField(choices=[('Orc', 'Orc'), ('Undead', 'Undead'), ('Tauren', 'Tauren'), ('Troll', 'Troll'), ('Blood Elf', 'Blood Elf'), ('Goblin', 'Goblin'), ('Pandaren', 'Pandaren')], max_length=8)),
                ('article_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('page_text', models.CharField(default='', max_length=1000)),
                ('article_creation_date', models.DateTimeField(null=True, verbose_name='creation_date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('article_created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
