# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliancecharacter',
            name='race',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='stuff.AllianceRaces'),
        ),
        migrations.AlterField(
            model_name='hordecharacter',
            name='race',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='stuff.HordeRaces'),
        ),
    ]
