# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_auto_20180515_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allianceraces',
            options={'verbose_name_plural': 'Alliance Races'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='horderaces',
            options={'verbose_name_plural': 'Horde Races'},
        ),
    ]
