# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_auto_20180521_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='allianceraces',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'images'),
        ),
        migrations.AddField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'images'),
        ),
        migrations.AddField(
            model_name='horderaces',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'images'),
        ),
    ]
