# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_auto_20180514_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliancecharacter',
            name='character_info',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='hordecharacter',
            name='character_info',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
