# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_auto_20180515_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='allianceraces',
            name='alliance_text',
            field=models.CharField(default=b'', max_length=9999),
        ),
        migrations.AddField(
            model_name='class',
            name='class_text',
            field=models.CharField(default=b'', max_length=9999),
        ),
        migrations.AddField(
            model_name='faction',
            name='faction_text',
            field=models.CharField(default=b'', max_length=9999),
        ),
        migrations.AddField(
            model_name='horderaces',
            name='horde_text',
            field=models.CharField(default=b'', max_length=9999),
        ),
    ]
