# Generated by Django 2.0.5 on 2018-05-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_auto_20180522_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliancecharacter',
            name='article_creation_date',
            field=models.DateTimeField(null=True, verbose_name='creation_date'),
        ),
        migrations.AlterField(
            model_name='alliancecharacter',
            name='character_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stuff.Class'),
        ),
        migrations.AlterField(
            model_name='alliancecharacter',
            name='character_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='alliancecharacter',
            name='faction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stuff.Faction'),
        ),
        migrations.AlterField(
            model_name='alliancecharacter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='alliancecharacter',
            name='race',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stuff.AllianceRaces'),
        ),
        migrations.AlterField(
            model_name='alliancecharacter',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stuff.Status'),
        ),
        migrations.AlterField(
            model_name='allianceraces',
            name='alliance_race',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='allianceraces',
            name='alliance_text',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_text',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='faction_name',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='faction',
            name='faction_text',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='hordecharacter',
            name='article_creation_date',
            field=models.DateTimeField(null=True, verbose_name='creation_date'),
        ),
        migrations.AlterField(
            model_name='hordecharacter',
            name='character_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stuff.Class'),
        ),
        migrations.AlterField(
            model_name='hordecharacter',
            name='character_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hordecharacter',
            name='faction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stuff.Faction'),
        ),
        migrations.AlterField(
            model_name='hordecharacter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='hordecharacter',
            name='race',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stuff.HordeRaces'),
        ),
        migrations.AlterField(
            model_name='hordecharacter',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stuff.Status'),
        ),
        migrations.AlterField(
            model_name='horderaces',
            name='horde_race',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='horderaces',
            name='horde_text',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
