# Generated by Django 2.0.4 on 2018-05-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0012_auto_20180511_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='faction_info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='faction',
            name='faction_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
