# Generated by Django 2.0.4 on 2018-05-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0013_auto_20180511_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
