# Generated by Django 2.0.4 on 2018-05-11 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stuff', '0014_auto_20180511_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='page',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='page',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='race',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='race',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='faction',
            name='article_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faction',
            name='article_creation_date',
            field=models.DateTimeField(null=True, verbose_name='creation_date'),
        ),
        migrations.AddField(
            model_name='page',
            name='article_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='article_creation_date',
            field=models.DateTimeField(null=True, verbose_name='creation_date'),
        ),
        migrations.AddField(
            model_name='race',
            name='article_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='race',
            name='article_creation_date',
            field=models.DateTimeField(null=True, verbose_name='creation_date'),
        ),
    ]
