# Generated by Django 2.0.4 on 2018-05-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0015_auto_20180511_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(default='', max_length=100)),
                ('allied_with', models.CharField(choices=[('Alliance', 'Alliance'), ('Horde', 'Horde')], default='none', max_length=8)),
                ('status', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead'), ('Incapacitated', 'Incapacitated'), ('Unknown', 'Unknown')], default='none', max_length=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='faction',
            name='article_created_by',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='article_creation_date',
        ),
        migrations.RemoveField(
            model_name='race',
            name='article_created_by',
        ),
        migrations.RemoveField(
            model_name='race',
            name='article_creation_date',
        ),
    ]
