# Generated by Django 2.0.4 on 2018-05-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0016_auto_20180511_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='allied_with',
            field=models.CharField(choices=[('Choose', 'Choose...'), ('Alliance', 'Alliance'), ('Horde', 'Horde')], default='none', max_length=8),
        ),
    ]
