# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0017_auto_20180511_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='allied_with',
            field=models.CharField(choices=[(b'Choose', b'Choose...'), (b'Alliance', b'Alliance'), (b'Horde', b'Horde')], default=b'', max_length=8),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[(b'Alive', b'Alive'), (b'Dead', b'Dead'), (b'Incapacitated', b'Incapacitated'), (b'Unknown', b'Unknown')], default=b'', max_length=8),
        ),
        migrations.AlterField(
            model_name='race',
            name='faction',
            field=models.CharField(choices=[(b'Alliance', b'Alliance'), (b'Horde', b'Horde'), (b'Allied', b'Allied Race')], default=b'', max_length=8),
        ),
    ]
