# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0018_auto_20180511_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[(b'Choose', b'Choose...'), (b'Alliance', b'Alliance'), (b'Horde', b'Horde')], default=b'', max_length=8),
        ),
    ]
