# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0019_character_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
    ]
